#!/bin/bash -l

# Function for printing and executing commands
cmd() {
  echo "+ $@";
  eval "$@";
}

for version in 3.10.19 3.11.14 3.12.12  3.13.12  3.14.3  #3.9.13 3.10.6 3.11.4 3.12.5 3.13.0 
do
	cmd "module load python/$version"
	cmd "python -m ensurepip --default-pip"
	cmd "python -m pip install --upgrade pip pipes "
        #cmd "pip install -r requirements.txt"
	cmd "python -mpip install -r requirements.txt"
	cmd "python -m pip install --upgrade pip setuptools wheel numpy scipy matplotlib jupyter pandas jupyterlab"
	cmd "python -m pip install reframe reframe-hpc==3.12.0 influxdb"
	
	# changes for reframe luncher 
	cmd "cp $(which reframe) $(which reframe)_backup"
	cmd "echo '#!/usr/bin/env python3'> $(which reframe)" 
	cmd "cat $(which reframe)_backup |tail -n+2>> $(which reframe)" 
	
	#cmd "module load cray-mpich"
	cmd "python -m pip install --no-cache-dir mpi4py"
	cmd "module unload python"
done 

