name: Gila aarch64 Ansible CI

on:
  pull_request:
    #    paths:
    #      - "gracehopper/**"

  workflow_dispatch:

  # Validate main branch updates
  push:
    branches:
      - main
      - develop

  schedule:
    - cron: "0 2 * * 0"


jobs:
  validate:

    runs-on: ubuntu-24.04-arm

    steps:

      - name: Checkout repository with roles
        uses: actions/checkout@v4
        with:
          submodules: recursive


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"


      - name: Install Ansible
        run: |
          pip install ansible ansible-lint yamllint


      - name: run playbook 
        run: |
          ansible-playbook \
            -vvv \
            gracehopper/playbook.yaml -e @group_vars.yml -e NSP_install_root=${{ github.workspace }}/gilaarm -e NSP_scratch_directory=${{ github.workspace }}/temp_scratch 
